package cn.wzvtcsoft.x.bos.domain;

// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.timbos.ActionScript3Plugin from BosEntity

import cn.wzvtcsoft.x.bos.domain.CoreObject;
import cn.wzvtcsoft.x.bos.domain.util.StringUtils;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import javax.persistence.*;

@EntityListeners(AuditingEntityListener.class)
@MappedSuperclass
@Access(AccessType.FIELD)
public abstract class BosEntity extends CoreObject implements IEntity {

    @Column(name="number",unique=true,nullable=false,length=25)
    private String number;

    @CreatedBy
    @Column(name="createactorid",length=25)
    private String createactorid;

    @LastModifiedBy
    @Column(name="updateactorid",length=25)
    private String updateactorid;

    @LastModifiedDate
    private long updatetime;

    @CreatedDate
    private long createtime;

   /* @Column(name="objectstatus",length=25)
    @Enumerated(EnumType.STRING)
    private EntityStatus objectstatus;



    public EntityStatus getObjectstatus() {
        return objectstatus;
    }
    public void setObjectstatus(EntityStatus objectstatus) {
        this.objectstatus = objectstatus;
    }
*/

    public String getCreateactorid() {
        return createactorid;
    }

    /* public void setCreateactorid(String createactorid) {
         this.createactorid = createactorid;
     }
 */
    public String getUpdateactorid() {
        return updateactorid;
    }

    public long getUpdatetime() {
        return updatetime;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public String getNumber() {
        return number;
    }

    /*   public void setUpdatetime(long updatetime) {
           this.updatetime = updatetime;
       }*/
    public long getCreatetime() {
        return createtime;
    }
/*
    public void setCreatetime(long createtime) {
        this.createtime = createtime;
    }
*/

    @PrePersist
    @PreUpdate
    protected void prePersistOrUpdate() {
        this.updatetime = System.currentTimeMillis();
        if (!StringUtils.hasText(number)) {
            this.number = ""+System.currentTimeMillis();
        }
    }


}
